spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  servlet:
    #    设置文件上传最大值
    multipart:
      max-file-size: 10MB

pagehelper:                #分页插件
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:

mybatis:
  type-aliases-package: com.blog.pojo   #设置别名
  mapper-locations: classpath:mapper/*.xml   #ָ指定myBatis的核心配置文件与Mapper映射文件

logging:  #日志级别
  level:
    root: info
    com.blog: debug
  file: log/blog-dev.log


  #开发环境
server:
  port: 8082
#自定义文件上传路径，用于Controller层
filePath: /home/image

ImageUpload:
  address: /usr/local/nginx/html/images/
  imageport: 80
  server: 192.168.7.109
  FTP_PORT: 21
  FTP_USERNAME: root
  FTP_PASSWORD: root
# file:
#  upload:
#    path: F://images/
#    relative: /images/**

