#开发环境
server:
  port: 8083
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  datasource:
    #数据库配置
    url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

#文件上传
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#plus 配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.lt.blog3.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




pagehelper:                #分页插件
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:


logging:  #日志级别
  level:
    root: info
    com.blog: debug
  file: log/blog-dev.log



#自定义文件上传路径，用于Controller层
filePath: /home/image


file:
  dirPath: ${DIR_PATH:/file} #这个是docker映射的路径,本地路径
  template:
    path: ${TEMPLATE_PATH:/templates} #这个是导出模板所有在的服务的域名(包括http://)
  isStatis: ${IS_STATIC:true} #表示是否做映射
  domain: ${DOMAIN:http://ltandqly.top/}
