spring:
  datasource:
    url: jdbc:mysql://8.129.124.133:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 102100lt

pagehelper:                #分页插件
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:

mybatis:
  type-aliases-package: com.blog.pojo   #设置别名
  mapper-locations: classpath:mapper/*.xml   #ָ指定myBatis的核心配置文件与Mapper映射文件

logging:  #日志级别
  level:
    root: info
    com.blog: debug
  file: log/blog-dev.log

  #开发环境
server:
  port: 80

# file:
#  upload:
#    path: F://images/
#    relative: /images/**
remoteServer.url : /home/image
remoteServer.username : root
remoteServer.password : 2000101LiuTao

file:
  dirPath: ${DIR_PATH:/home/image} #这个是docker映射的路径,本地路径
  template:
    path: ${TEMPLATE_PATH:/templates} #这个是导出模板所有在的服务的域名(包括http://)
  isStatis: ${IS_STATIC:true} #表示是否做映射
  domain: ${DOMAIN:http://ltandqly.top/}
